#! /usr/bin/env bash
echo "Saving list of current vscode extensions..."
./script/vscode/save_vscode_exts.sh
echo "Checking for changes to install_vscode_exts..."
git add script/vscode/install_vscode_exts.sh

# commit current version of nvim (Lazy) plugins catalogue
echo "Checking for changes to lazy-lock.json..."
echo
git add nvim/.config/nvim/lazy-lock.json
