{
  config,
  lib,
  ...
}:

with lib;
let
  cfg = config.nyx.shell.bash;
in
{
  options.nyx.shell.bash = {
    enable = mkEnableOption "bash configuration";

    profileExtra = mkOption {
      default = "";
      type = types.lines;
      description = ''
        Extra commands that should be run when initializing a login
        shell.
      '';
    };

    initExtra = mkOption {
      default = "";
      type = types.lines;
      description = ''
        Extra commands that should be run when initializing an
        interactive shell.
      '';
    };
  };

  config = mkIf cfg.enable {
    programs.bash = {
      enable = true;
      enableCompletion = true;
      historyFile = "${config.xdg.configHome}/bash/.bash_history";
      initExtra = # bash
        ''
          # auto generated by nyx

          ${cfg.profileExtra}
        '';
      profileExtra = # bash
        ''
          # auto generated by nyx

          ${cfg.initExtra}
        '';
    };
  };
}
