# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "nvidia" ];
  boot.kernelModules = [ "kvm-amd" "nvidia" ];
  boot.extraModulePackages = [ ];

  # Asus kernel patches
 #  boot.kernelPatches = let
 #     version = config.boot.kernelPackages.kernel.version;
 # in [
 #   {
 #     name = "g14";
 #     patch = builtins.fetchurl {
        # url = "https://gitlab.com/dragonn/linux-g14/-/raw/${lib.versions.majorMinor version}/asus-patch-series.patch";
        # url = "https://gitlab.com/asus-linux/fedora-kernel/-/raw/rog-${lib.versions.majorMinor version}/asus-patch-series.patch";
 #        url = "https://gitlab.com/asus-linux/linux-g14/-/raw/${lib.versions.majorMinor version}/asus-patch-series.patch";
 #       sha256 = "0fgbv87z7jyi6f2y0mm246pv7p0nhvznpbmdlf04gl9xinvs2g5m";
 #     };
      # structuredExtraConfig = with lib.kernel; {
      #   ASUS_ARMOURY = module;
        # ASUS_WMI_BIOS = yes;
      # };
 #     extraMeta = {
 #       branch = lib.versions.majorMinor version;
 #     };
 #   }
 # ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f8d2d292-064d-403d-8578-cddd38a090e8";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f8d2d292-064d-403d-8578-cddd38a090e8";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/f8d2d292-064d-403d-8578-cddd38a090e8";
      fsType = "btrfs";
      options = [ "compress=zstd" "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EE2C-39D6";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/24B4-5D5C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ { device = "/swap/swapfile"; size = 8*1024; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
