# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
let
  commonOptions = [
    "defaults"
    "discard"
    "noatime"
  ];
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ "nvidia" ];
  boot.kernelModules = [
    "kvm-amd"
    "nvidia"
  ];
  boot.extraModprobeConfig = # bash
    ''
      # Add the S0ix module parameter
      options nvidia "NVreg_EnableS0ixPowerManagement=1"
      # make the PreserveVideo... option explicit, and set a Temporary File Path to prevent errors
      options nvidia "NVreg_PreserveVideoMemoryAllocations=1"
      options nvidia "NVreg_TemporaryFilePath=/var/tmp"
      # set the default state of function lock (workaround for lack of Fn-Esc toggle)
      # NB: as at 8/01/2025, this is changing the value but the function lock is still fixed on
      options asus_wmi fnlock_default=N
    '';
  boot.extraModulePackages = [ ];

  boot.supportedFilesystems = [
    "ntfs" # required to mount ntfs partitions
  ];

  # Asus kernel patches
  #  boot.kernelPatches = let
  #     version = config.boot.kernelPackages.kernel.version;
  # in [
  #   {
  #     name = "g14";
  #     patch = builtins.fetchurl {
  # url = "https://gitlab.com/dragonn/linux-g14/-/raw/${lib.versions.majorMinor version}/asus-patch-series.patch";
  # url = "https://gitlab.com/asus-linux/fedora-kernel/-/raw/rog-${lib.versions.majorMinor version}/asus-patch-series.patch";
  #        url = "https://gitlab.com/asus-linux/linux-g14/-/raw/${lib.versions.majorMinor version}/asus-patch-series.patch";
  #       sha256 = "0fgbv87z7jyi6f2y0mm246pv7p0nhvznpbmdlf04gl9xinvs2g5m";
  #     };
  # structuredExtraConfig = with lib.kernel; {
  #   ASUS_ARMOURY = module;
  # ASUS_WMI_BIOS = yes;
  # };
  #     extraMeta = {
  #       branch = lib.versions.majorMinor version;
  #     };
  #   }
  # ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f8d2d292-064d-403d-8578-cddd38a090e8";
    fsType = "btrfs";
    options = commonOptions ++ [
      "compress=zstd"
      "subvol=root"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/f8d2d292-064d-403d-8578-cddd38a090e8";
    fsType = "btrfs";
    options = commonOptions ++ [
      "compress=zstd"
      "subvol=home"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/f8d2d292-064d-403d-8578-cddd38a090e8";
    fsType = "btrfs";
    options = commonOptions ++ [
      "compress=zstd"
      "subvol=nix"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EE2C-39D6";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/24B4-5D5C";
    fsType = "vfat";
    # set these permissions to prevent the "random seed file is world accessible which is a security hole" boot error
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # mount the main Windows 11 Pro partition
  fileSystems."/mnt/win11pro" = {
    device = "/dev/disk/by-uuid/D02CB4C42CB4A73E";
    fsType = "ntfs-3g";
    options = [
      "rw"
      "uid=1000"
      "windows_names"
    ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/adadd3b9-e1ca-415d-a8a0-0d06e711f71b";
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Update the CPU microcode for AMD processors
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
