# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  # enable ntfs support at boot
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/70ac56cd-aff5-42bd-bf1b-607f72fec071";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DE8D-6ECE";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/os_share" = {
    device = "/dev/disk/by-uuid/19B5-8B3D";
    fsType = "vfat";
    options = [
      "fmask=0002"
      "dmask=0002"
      # this makes it visible in the gnome files manager (nautilus)
      "x-gvfs-show"
    ];
  };

  fileSystems."/mnt/bootcamp" = {
    device = "/dev/disk/by-uuid/2B83BD105D4F5763";
    fsType = "ntfs-3g";
    options = [
      "rw"
      "uid=1000"
      "windows_names"
    ];
  };

  # mount the system APFS partition to hide it from the Gnome Files (nautilus) app sidebar
  fileSystems."/mnt/macos" = {
    device = "/dev/disk/by-uuid/f089a798-365d-41da-adbd-e7ce1965a6be";
    fsType = "apfs";
    options = [
      "vol=0"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/6168b61a-6647-4096-8f4d-7cf5856524d4"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
