return {
  "nvim-lua/plenary.nvim", -- lua functions that many plugins use
  "christoomey/vim-tmux-navigator", -- tmux & split window navigation
  "b0o/schemastore.nvim", -- JSON schemas for Neovim
  -- { import = "plugins.alpha" },
  -- { import = "plugins.auto-session" },
  -- { import = "plugins.autopairs" },
  -- { import = "plugins.better-escape" },
  -- { import = "plugins.bufferline" },
  -- { import = "plugins.colorscheme" },
  -- { import = "plugins.comment" },
  -- { import = "plugins.dap" },
  -- { import = "plugins.dressing" },
  -- { import = "plugins.flash" },
  -- { import = "plugins.formatting" },
  -- { import = "plugins.gitsigns" },
  -- { import = "plugins.harpoon" },
  -- { import = "plugins.indent-blankline" },
  -- { import = "plugins.lazygit" },
  -- { import = "plugins.linting" },
  -- { import = "plugins.lualine" },
  -- { import = "plugins.noice" },
  -- { import = "plugins.nvim-cmp" },
  { import = "plugins.nvim-tree" },
  -- { import = "plugins.nvim-treesitter-text-objects" },
  -- { import = "plugins.render-markdown" },
  -- { import = "plugins.substitute" },
  -- { import = "plugins.surround" },
  -- { import = "plugins.telescope" },
  -- { import = "plugins.todo-comments" },
  -- { import = "plugins.treesitter" },
  -- { import = "plugins.trouble" },
  -- { import = "plugins.vim-maximise" },
  -- { import = "plugins.which-key" },
  -- { import = "plugins.lsp.lspconfig" },
  -- { import = "plugins.lsp.mason" },
}
