#! /usr/bin/env bash

scriptDir=$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")"])
cd "$scriptDir" || exit

# Download the git script for fzf
git clone git@github.com:junegunn/fzf-git.sh.git ~/

# This has to be applied after brew has installed cask logi-options-plus
patch /Library/Application\ Support/Logitech.localized/LogiOptionsPlus/app_permissions.json <./app_permissions.json.diff

# Download theme after brew has installed bat
curl -O "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_night.tmTheme --create-dirs --output $(bat --config-dir)/themes"

# Set up symlink for vscode command line binary
ln -s "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code" /usr/local/bin/code

# Execute after vscode is installed
./vscode/save_vscode_exts.sh
./vscode/install_vscode_exts.sh # must execute this before enabling git hooks in next command

# Point git to config file within repo containing path to custom githooks directory
git config --local include.path ../.gitconfig

# Download and build Zeal (execute after dependencies (eg. qt) are installed by Brewfile)
export CMAKE_PREFIX_PATH="$(brew --prefix qt@6):$(brew --prefix libarchive):$(brew --prefix vulkan-headers)"
git clone https://github.com/zealdocs/zeal.git "$devfiles/git_repos/package_repos/zealdocs"
cd "$devfiles/git_repos/package_repos/zealdocs/zeal" || exit
mkdir build
cmake -S . -B build
cmake --build build --config Release --parallel
cp -Rp build/Zeal.app /Applications/
cd "$scriptDir" || exit
