#! /usr/bin/env bash
./scripts/vscode/save_vscode_exts.sh
git add scripts/vscode/install_vscode_exts.sh

# commit current version of nvim (Lazy) plugins catalogue
git add nvim/.config/nvim/lazy-lock.json
