#:schema https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json
#
# indentation is not needed but it makes it easier to read ;)
#
version = "1"

[global]
  initialize = true
  # prevent idle sleeping
  prevent-sleep = true
  # normally running overnight
  priority = "high"

[default]
  description = "Restic backup of user timotheos on host mack"
  option = [
    # default for rclone.args is "serve restic --stdio --b2-hard-delete"
    'rclone.args=serve restic --stdio --b2-hard-delete --fast-list --log-file=/Users/timotheos/Library/Logs/restic/mack-timotheos-b2rcl_{{ .Now.Format "2006-01-02" }}.log --stats 2m --verbose --checkers 100 --transfers 100 --order-by size,mixed,75 --max-backlog 10000',
    "rclone.connections=100",
  ]
  # default is 16MB, increase for a mix of small and large files
  pack-size = 128
  password-file = "../sops-nix/secrets/users/timotheos/restic_b2_mack-timotheos"
  repository = "rclone:b2:mack-timotheos"
  # true = 1, set to 2 for more detail (eg. lists all files in source repo and their status)
  verbose = 1

  [default.env]
    # Point restic to the user home when running via root as a system daemon 
    HOME = "/Users/timotheos"

  [default.backup]
    # set to true for testing
    dry-run = false
    source = ["/Users/timotheos"]
    # set to false as "restic check" is a data intensive operation
    # see the discussion at https://forum.restic.net/t/unexpected-costs-with-backblaze-b2-backend/4176/5
    check-before = false
    exclude-file = "./exclude_home.txt"
    exclude-caches = true
    # read more files concurrently (default is 2)
    read-concurrency = 100
    # SCHEDULING
    # run the backup daily at 12:30 am
    schedule = "*-*-* 00:30"
    schedule-permission = "system"
    schedule-priority = "standard"
    # save the log to ~/Library/Logs/restic (NB: restic uses standard POSIX redirection for logging, as there is no log file parameter)
    # NB: use single quotes as escaping inline double quotes does not work
    schedule-log = '../../Library/Logs/restic/mack-timotheos-b2bak_{{ .Now.Format "2006-01-02 15:04:05" }}.log'
    schedule-lock-wait = "5m"

    # send monitoring info to healthchecks.io
    [[default.backup.send-before]]
      method = "HEAD"
      url = "https://hc-ping.com/42a6053f-8428-43a2-bf57-5394990b3e38/start"

    [[default.backup.send-after]]
      method = "HEAD"
      url = "https://hc-ping.com/42a6053f-8428-43a2-bf57-5394990b3e38"

    [default.backup.send-after-fail]
      method = "POST"
      url = "https://hc-ping.com/42a6053f-8428-43a2-bf57-5394990b3e38/fail"
      body-template = "body-template.json"

      [[default.backup.send-after-fail.headers]]
        name = "Content-Type"
        value = "text/plain; charset=UTF-8"

  [default.forget]
    # set to true for first run
    dry-run = true
    host = "mack"
    prune = true
    keep-last = 10
    keep-daily = 7
    keep-weekly = 12
    keep-monthly = 24
    keep-yearly = 25
    # SCHEDULING
    # run a forget and prune operation on Mondays at 1:30 am
    schedule = "Mon *-*-* 01:30"
    schedule-permission = "system"
    schedule-priority = "background"
    schedule-log = '../../Library/Logs/restic/mack-timotheos-b2prune_{{ .Now.Format "2006-01-02 15:04:05" }}.log'
    schedule-lock-wait = "5m"

    # send monitoring info to healthchecks.io
    [default.forget.send-before]
      method = "HEAD"
      url = "https://hc-ping.com/b14dac3a-79ae-4bac-89aa-4751c7603b50/start"

    [default.forget.send-after]
      method = "HEAD"
      url = "https://hc-ping.com/b14dac3a-79ae-4bac-89aa-4751c7603b50"

    [default.forget.send-after-fail]
      method = "POST"
      url = "https://hc-ping.com/b14dac3a-79ae-4bac-89aa-4751c7603b50/fail"
      body-template = "body-template.json"

      [[default.forget.send-after-fail.headers]]
        name = "Content-Type"
        value = "text/plain; charset=UTF-8"

  [default.check]
    # run an integrity check on the 1st of each month at 2 am
    schedule = "*-*-1 02:00"
    schedule-permission = "system"
    schedule-priority = "background"
    schedule-log = '../../Library/Logs/restic/mack-timotheos-b2check_{{ .Now.Format "2006-01-02 15:04:05" }}.log'
    schedule-lock-wait = "5m"

    # send monitoring info to healthchecks.io
    [default.check.send-before]
      method = "HEAD"
      url = "https://hc-ping.com/4b6b82d9-1088-4763-8129-2ce1f996b682/start"

    [default.check.send-after]
      method = "HEAD"
      url = "https://hc-ping.com/4b6b82d9-1088-4763-8129-2ce1f996b682"

    [default.check.send-after-fail]
      method = "POST"
      url = "https://hc-ping.com/4b6b82d9-1088-4763-8129-2ce1f996b682/start"
      body-template = "body-template.json"

      [[default.check.send-after-fail.headers]]
        name = "Content-Type"
        value = "text/plain; charset=UTF-8"
