[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs

[AutoRun]
enabled=false
program=

[BitTorrent]
Session\DefaultSavePath=/downloads/completed
Session\ExcludedFileNames=
Session\Interface=tun0
Session\InterfaceAddress=0.0.0.0
Session\InterfaceName=tun0
Session\Port=37847
Session\QueueingSystemEnabled=true
Session\SSL\Port=39566
Session\TempPath=/downloads/incomplete
Session\TempPathEnabled=true

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
General\Locale=en
MailNotification\req_auth=true
WebUI\Address=*
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(yzPnuj6MOQhyNtLC1EWu9w==:XZqh6p78dx+0w195R96Um4VdqItkRMALLzZ7YHhFAB+6xBMAA9ibeQQ3nnQPq6GXe18ymperArwKsTLXcb1aAQ==)"
WebUI\Port=8090
WebUI\ServerDomains=*
WebUI\Username=mettavi

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
